language: node_js
node_js:
  - "0.12"
  - "iojs"
sudo: required
before_script:
  - sudo sh -c "echo 'deb http://download.mono-project.com/repo/debian wheezy main' > /etc/apt/sources.list.d/mono-xamarin.list"
  - sudo sh -c "echo 'deb http://download.mono-project.com/repo/debian wheezy-libtiff-compat main' >> /etc/apt/sources.list.d/mono-xamarin.list"
  - sudo apt-get update -qq
  - sudo apt-get install --force-yes mono-devel
