language: csharp
mono:
- beta
env:
- TRAVIS: true
sudo: required
before_script:
- sudo apt-get install build-essential
- sudo apt-get install python libssl-dev curl
- curl https://raw.github.com/creationix/nvm/master/install.sh | sh
- nvm install 0.12
script:
- ". ./travis-build.sh"
- npm install
- npm test
deploy:
  provider: npm
  email: david.driscoll@gmail.com
  api_key:
    secure: dlMX8XtGw+opljevthxhEbRQFlJDiymowv4vHw/cvYSOm31flDJiZ+nljioQ72FEjWYGM8ZtcO8/j90gH8l9WeCAmE/JC0bc57MCSbxkTBifb1HYiPsgZfls1K5E8KlCv1WQEu7+Gfk0fGqiemOjAFL9+YDGMA8vdtT2LFH1jaY=
  on:
    tags: true
    repo: OmniSharp/omnisharp-node-client
after_deploy:
- cat npm-debug.log
