language: csharp
mono:
  - beta
sudo: false
env:
  global:
    - secure: ROHqg+6judrm6g8HYMAFX0tGLeLYKcUGEvQjnzw57Z7PjuaedUYdYFnPhGKW9AfodsP0Kf2zC5CuKZXmAZ/WO8qgAcj4IyIcxxi4LDFRu1D7XslEmjKc8bgVOAtUQKTZrL60JWVDozqREn4W4eWRILVejl9kDKKZ2xZkGPLDb/A=
    - secure: G2JHZZ38SRPa+/vLULCjPW/QyL3fAIPtASUbB0blTaTdZBs7uLi8ozgTfuzGVcT6rcYSh1pr0w7wJ79tjE4UFlA1oYVhrr851hVj0muHs/ZxdBVBgpKs07O8t/f50/b42RVFA+irpjg2lK+uJBZfNHPmkJaCbZGvZfHjcLect6g=
addons:
  apt:
    packages:
      - curl
before_script:
  - curl https://raw.github.com/creationix/nvm/master/install.sh | sh
  - nvm install 0.12
  - chmod +x build-server.sh
  - chmod +x publish.sh
script:
  - ". ./build-server.sh"
  - npm install
  - npm test
after_success:
  - echo TRAVIS_SECURE_ENV_VARS = $TRAVIS_SECURE_ENV_VARS
  - echo TRAVIS_BRANCH = $TRAVIS_BRANCH
  - echo TAG_COMMIT = $TAG_COMMIT
  - ". ./publish.sh"
before_install:
  - openssl aes-256-cbc -K $encrypted_43a97f4523d0_key -iv $encrypted_43a97f4523d0_iv -in travis_id_rsa.enc -out ~/.ssh/id_rsa -d
